config/routes.rb
Rails.application.routes.draw do


  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end

  devise_for :users
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, except: [:index, :new, :create]

  #Get /articles
  def index
    @articles = Article.all
  end

  #Get /articles/:id


  def show
    @comment = Comment.new
  end

  def edit

  end

  def new
    @article = Article.new
  end

  def create

    @article = current_user.articles.new(article_param)

    @user = current_user.articles.new(article_param)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def update


    if @article.update_attributes(article_param)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_param
    params.require(:article).permit(:title, :body)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user!



  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :article_id, :body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1> Edit, your article!!! </h1>
<!--objeto del modelo-->
<%= form_for(@article) do |f| %>

<div class="container">
  <div>
    <%= f.text_field :title, placeholder:"Title", class: "form-control" %>
  </div>

  <div>
    <%= f.text_area :body, placeholder:"Write your content", class: "form-control" %>
  </div>

  <div>
    <%= f.submit "Publish", class: "btn btn-primary btn-lg btn-block"     %>
  </div>

</div>
<%end%>

app/views/articles/index.html.erb
<%= @articles.each do |article| %>
<h1><%= link_to article.title, article %> </h1>
<div>
  <%= article.body %> - <%= link_to "Delete", article, method: :delete %>
  <% unless article.user.nil? %>
  <p> Written by <%=  article.user.email  %></p>
  <% end %>
  <br>
</div>
<% end %>

app/views/articles/new.html.erb
<h1> Post, your article!!! </h1>
<!--objeto del modelo-->
<%= form_for(@article) do |f| %>

<div class="container">
  <div>
    <%= f.text_field :title, placeholder:"Title", class: "form-control" %>
  </div>

  <div>
    <%= f.text_area :body, placeholder:"Write your content", class: "form-control" %>
  </div>

  <div>
    <%= f.submit "Publish", class: "btn btn-primary btn-lg btn-block"     %>
  </div>

</div>
<%end%>

app/views/articles/show.html.erb
<h1> <%=  @article.title  %></h1>
<p> <%=  @article.body  %></p>
<% unless @article.user.nil? %>
<p>Written by <%=  @article.user.email  %></p>
<% end %>

<div>
  <strong> Comments: </strong>
  <%= render "comments/form" %>
</div>
<ul>
  <%= @article.comments.each do |comment| %>
  <li>
    <%= comment.body %> By <%= comment.user.email %>
  </li>
  <% end %>
</ul>


<%= link_to "Edit!", edit_article_path(@article) %>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Bodywebdewhb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>

  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gabriel's Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Gabriel's blog</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "All post", articles_path %>
            </li>

            <% if user_signed_in? %>
            <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
            <%else%>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>


            <%end%>


          </ul>
          <!--<form id="signin" class="navbar-form navbar-right" role="form">-->
            <!--<div class="input-group">-->
              <!--<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>-->
              <!--<input id="email" type="email" class="form-control" name="email" value="" placeholder="Email Address">-->
              <!--</div>-->

            <!--<div class="input-group">-->
              <!--<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>-->
              <!--<input id="password" type="password" class="form-control" name="password" value="" placeholder="Password">-->
              <!--</div>-->

            <!--<button type="submit" class="btn btn-primary">Login</button>-->
            <!--</form>-->

        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%  if user_signed_in?  %>
<h1>Bienvenido al blog!!! <%= current_user.email%>    </h1>

<%end%>